### ISSUE TITLE
CPM module build error

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/pipeline#6] opened 2015-12-20 13:06 UTC
See error log:

``` c++
In file included from /mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/Localizer.cpp:1:0:
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/../Localizer.h:44:21: error: 'DataTransformer' is not a member of 'caffe'
     std::unique_ptr<caffe::DataTransformer<float>> _caffeTransformer;
                     ^
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/../Localizer.h:44:21: error: 'DataTransformer' is not a member of 'caffe'
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/../Localizer.h:44:49: error: template argument 1 is invalid
     std::unique_ptr<caffe::DataTransformer<float>> _caffeTransformer;
                                                 ^
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/../Localizer.h:44:49: error: template argument 2 is invalid
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/Localizer.cpp: In member function 'std::vector<pipeline::Tag> pipeline::Localizer::filterTagCandidates(std::vector<pipeline::Tag>&&)':
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/Localizer.cpp:310:22: error: base operand of '->' is not a pointer
     _caffeTransformer->Transform(data, &caffeData);
                      ^
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/Localizer.cpp: In member function 'void pipeline::Localizer::initializeDeepLocalizer(deeplocalizer::CaffeClassifier*)':
/mnt/ImageCompressBuild2/cpm-packages/modules/github_bioroboticslab_pipeline_cpm/src/pipeline/src/Localizer.cpp:348:27: error: cannot convert 'std::_MakeUniq<caffe::DataTransformer<float> >::__single_object {aka std::unique_ptr<caffe::DataTransformer<float> >}' to 'int' in assignment
         _caffeTransformer = std::make_unique<caffe::DataTransformer<float>>(
                           ^
make[2]: *** [cpm-bin/github_bioroboticslab_pipeline_cpm/bin/CMakeFiles/github_bioroboticslab_pipeline_cpm.dir/pipeline/src/Localizer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```

**Comment by nebw** [comment] 2015-12-21 22:39
The problem is that you are still using the 'cpm' branch of the pipeline repository. This should be fixed on the master branch. I should probably remove the cpm branch asap...

**Closed as completed by nebw** 2015-12-21 22:39 UTC
